import re
import logging
import time
import threading
from typing import List, Callable, Optional, Dict, Any, Set
from .models import GeneratorConfig, ColumnDefinition, RowData, ColumnType
from .llm_client import LLMClient
from .validator import UniquenessValidator
from .analytics import QualityAnalyzer
from .exporters import PDFReportGenerator
import pandas as pd

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class GeneratorController:
    def __init__(self):
        self.config = GeneratorConfig(model_id="local-model") # Default, wil be updated
        self.columns: List[ColumnDefinition] = []
        self.execution_order: List[ColumnDefinition] = [] # Sorted columns
        self.generated_rows: List[RowData] = []
        
        self.llm_client: Optional[LLMClient] = None
        self.llm_client: Optional[LLMClient] = None
        self.validator: Optional[UniquenessValidator] = None
        self.analyzer = QualityAnalyzer()
        self.pdf_exporter = PDFReportGenerator()
        
        # Metrics Tracking (Phase 10)
        self.metrics = {
            "faker_cols": 0,  # Number of columns generated deterministically (saved tokens)
            "llm_cols": 0,    # Number of columns generated by LLM
        }
        
        # Phase 5: Faker
        try:
            from faker import Faker
            self.fake = Faker()
        except ImportError:
            self.fake = None
            self.log("Warning: Faker library not found. Deterministic columns will fail.")
        
        self.is_running = False
        self.stop_requested = False
        
        # Callbacks
        self.on_progress: Optional[Callable[[int, int], None]] = None # current, total
        self.on_log: Optional[Callable[[str], None]] = None
        self.on_finished: Optional[Callable[[], None]] = None
        
    def initialize(self, config: GeneratorConfig, columns: List[ColumnDefinition]):
        self.config = config
        self.columns = columns
        self.llm_client = LLMClient(config, on_log=self.log)
        self.validator = UniquenessValidator(config)
        self.generated_rows = []
        self.stop_requested = False
        
        # Reset specific run metrics
        self.metrics = {
            "faker_cols": 0,
            "llm_cols": 0,
        }
        
        # Calculate execution order based on dependencies
        try:
            self.execution_order = self._get_execution_order(columns)
            self.log(f"Execution order resolved: {[c.name for c in self.execution_order]}")
        except Exception as e:
            self.log(f"Dependency Error: {e}")
            raise e
        
    def log(self, message: str):
        logger.info(message)
        if self.on_log:
            self.on_log(message)

    def _get_dependencies(self, prompt: str) -> Set[str]:
        """Extract valid column references from prompt like @[col_name]."""
        matches = re.findall(r'@\[(.*?)\]', prompt)
        return set(matches)

    def _get_execution_order(self, columns: List[ColumnDefinition]) -> List[ColumnDefinition]:
        """Topological sort of columns based on prompt dependencies."""
        col_map = {col.name: col for col in columns}
        adj_list: Dict[str, Set[str]] = {col.name: set() for col in columns}
        in_degree: Dict[str, int] = {col.name: 0 for col in columns}
        
        # Build Graph
        for col in columns:
            deps = self._get_dependencies(col.prompt_instruction)
            for dep_name in deps:
                if dep_name in col_map:
                    # dep_name must be generated BEFORE col
                    # Edge: dep_name -> col
                    adj_list[dep_name].add(col.name)
                    in_degree[col.name] += 1
                else:
                    self.log(f"Warning: Column '{col.name}' references unknown column '{dep_name}'. Ignoring.")

        # Kahn's Algorithm
        queue = [name for name, deg in in_degree.items() if deg == 0]
        sorted_cols = []
        
        while queue:
            node = queue.pop(0)
            sorted_cols.append(col_map[node])
            
            for neighbor in adj_list[node]:
                in_degree[neighbor] -= 1
                if in_degree[neighbor] == 0:
                    queue.append(neighbor)
                    
        if len(sorted_cols) != len(columns):
            raise ValueError("Circular dependency detected in column prompts!")
            
        return sorted_cols

    def _construct_prompt(self, col: ColumnDefinition, row_data: Dict[str, Any]) -> str:
        """Create a prompt for a single column value, interpolating dependencies."""
        
        # Interpolate dependencies
        instruction = col.prompt_instruction
        deps = self._get_dependencies(instruction)
        for dep in deps:
            if dep in row_data:
                val = str(row_data[dep])
                instruction = instruction.replace(f"@[{dep}]", val)
        
        constraints_text = ""
        if col.constraints.min_length:
            constraints_text += f"\n- Minimum length: {col.constraints.min_length} characters"
        if col.constraints.max_length:
            constraints_text += f"\n- Maximum length: {col.constraints.max_length} characters"
        if col.constraints.options:
             constraints_text += f"\n- Choose strictly from: {', '.join(col.constraints.options)}"
             
        prompt = (
            f"Generate a single {col.type.value} value for a database column named '{col.name}'.\n"
            f"Context/Description: {instruction}\n"
            f"Constraints: {constraints_text}\n"
            "Return ONLY the value. Do not include quotes or markdown formatting if possible."
        )
        return prompt

    def generate_row(self, initial_context: Optional[Dict[str, Any]] = None) -> Optional[RowData]:
        from core.row_agent import create_row_generator_graph
        
        # Prepare initial data
        row_data: Dict[str, Any] = initial_context.copy() if initial_context else {}
        
        # Pre-fill deterministic logic (Faker, Auto-Increment) BEFORE Agent
        # Because we want the Agent to focus on semantic LLM work.
        for col in self.execution_order:
            if col.name in row_data: continue
            
            if col.type == ColumnType.AUTO_INCREMENT:
                row_data[col.name] = len(self.generated_rows) + 1
                self.metrics["faker_cols"] += 1
            
            elif col.type == ColumnType.DETERMINISTIC and self.fake:
                provider = col.constraints.faker_provider or "name"
                try:
                    if hasattr(self.fake, provider):
                        func = getattr(self.fake, provider)
                        row_data[col.name] = str(func())
                    else:
                        row_data[col.name] = self.fake.name()
                    self.metrics["faker_cols"] += 1
                except:
                    pass

        # If all cols are filled (purely deterministic), skip agent
        if len(row_data) == len(self.columns):
            return RowData(data=row_data)

        # Filter out columns that are strictly "(Imported)"
        # These should NOT be touched by the LLM, and should NOT be validated strictly.
        agent_cols = [
            col for col in self.execution_order 
            if col.prompt_instruction != "(Imported)" 
            and col.name not in row_data
        ]
        
        # Track LLM columns (cols that WILL be generated by agent)
        self.metrics["llm_cols"] += len(agent_cols)
        
        # Additional check: If a column IS imported but the user changed the prompt, 
        # it will fall into agent_cols (if not matches "(Imported)").
        # But if it IS "(Imported)", we trust the value in row_data.

        # Agentic Generation for LLM columns
        try:
            agent = create_row_generator_graph(self.llm_client)
            
            initial_state = {
                "row_data": row_data,
                "columns": agent_cols, # Only generate non-imported, missing columns
                "errors": [],
                "attempt_count": 0,
                "is_valid": False
            }
            
            final_state = agent.invoke(initial_state)
            
            result_data = final_state['row_data']
            is_valid = final_state['is_valid']
            
            if not is_valid and final_state['attempt_count'] >= 3:
                self.log(f"Row generation failed validation: {final_state.get('errors')}")
                return None
                
            # Perform strict Uniqueness/Regex constraints check (Post-Agent Guardrails)
            for col in self.columns:
                # SKIP validation for (Imported) columns - trust the source data
                if col.prompt_instruction == "(Imported)":
                    continue

                val = result_data.get(col.name)
                if not val: return None
                
                # Regex
                if not self.validator.validate_regex(val, col.constraints.regex_pattern):
                    self.log(f"Regex failed for {col.name}: {val}")
                    return None
                    
                # Uniqueness
                if not col.constraints.allow_duplicates:
                    if not self.validator.is_unique(val, field_type=col.type.value):
                        self.log(f"Duplicate value for {col.name}: {val}")
                        return None
                        
            # Commit unique values
            for col in self.columns:
                if not col.constraints.allow_duplicates:
                    val = result_data.get(col.name)
                    self.validator.commit(val, field_type=col.type.value)

            return RowData(data=result_data)

        except Exception as e:
            self.log(f"Agent error: {e}")
            return None

    def start_generation_thread(self):
        """Starts generation in a separate thread."""
        self.is_running = True
        t = threading.Thread(target=self._run_generation_loop)
        t.start()
        
    def stop_generation(self):
        print("DEBUG: Controller stop_generation called")
        self.stop_requested = True
        self.log("Stopping generation...")

    def _run_generation_loop(self):
        target_count = len(self.config.existing_data) if self.config.existing_data else self.config.num_rows
        self.log(f"Starting generation attempt for {target_count} rows...")
        
        consecutive_failures = 0
        MAX_CONSECUTIVE_FAILURES = 10  # Hard safeguard against infinite loops
        
        self.metrics["start_time"] = time.time()
        self.metrics["end_time"] = None
        self.metrics["last_row_time"] = self.metrics["start_time"]
        self.metrics["total_attempts"] = 0
        self.metrics["failed_attempts"] = 0
        
        # Mode A: Enrichment (Existing Data)
        if self.config.existing_data:
            for i, context_row in enumerate(self.config.existing_data):
                if self.stop_requested:
                    break
                
                # Check safeguards
                if consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                    self.log(f"CRITICAL: Aborting generation after {MAX_CONSECUTIVE_FAILURES} consecutive failures. Please check your constraints.")
                    break

                self.metrics["total_attempts"] += 1
                row = self.generate_row(initial_context=context_row)
                if self.stop_requested: break
                
                if row:
                    self.generated_rows.append(row)
                    self.metrics["last_row_time"] = time.time()
                    self.log(f"Generated row {len(self.generated_rows)}/{target_count}")
                    consecutive_failures = 0 # Reset on success
                else:
                    self.metrics["failed_attempts"] += 1
                    self.log(f"Row {i+1} enrichment failed. Skipping.")
                    consecutive_failures += 1
                
                if self.on_progress:
                    self.on_progress(len(self.generated_rows), target_count)
                    
        # Mode B: Fresh Generation
        else:
            while len(self.generated_rows) < target_count:
                if self.stop_requested:
                    break
                
                if consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                    self.log(f"CRITICAL: Aborting generation after {MAX_CONSECUTIVE_FAILURES} consecutive failures. Please check your constraints.")
                    break
                    
                self.metrics["total_attempts"] += 1
                row = self.generate_row()
                if self.stop_requested: break
                
                if row:
                    self.generated_rows.append(row)
                    self.metrics["last_row_time"] = time.time()
                    self.log(f"Generated row {len(self.generated_rows)}/{target_count}")
                    consecutive_failures = 0 # Reset on success
                    if self.on_progress:
                        self.on_progress(len(self.generated_rows), target_count)
                else:
                    self.metrics["failed_attempts"] += 1
                    self.log("Row generation failed. Retrying...")
                    consecutive_failures += 1
        
        self.metrics["end_time"] = time.time()
        self.is_running = False
        self.log("Generation finished.")
        if self.on_finished:
            self.on_finished()

    def export_csv(self, filepath: str):
        import csv
        if not self.generated_rows:
            return
            
        fieldnames = [col.name for col in self.columns]
        
        try:
            with open(filepath, 'w', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                writer.writeheader()
                for row in self.generated_rows:
                    writer.writerow(row.data)
            self.log(f"Exported to {filepath}")
        except Exception as e:
            self.log(f"Export failed: {e}")

    def export_json(self, filepath: str):
        import json
        if not self.generated_rows:
            return
        
        try:
            data = [row.data for row in self.generated_rows]
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=4)
            self.log(f"Exported to {filepath}")
        except Exception as e:
            self.log(f"JSON Export failed: {e}")

    def export_sql(self, filepath: str, table_name: str = "synthetic_data"):
        if not self.generated_rows:
            return
            
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                for row in self.generated_rows:
                    cols = []
                    vals = []
                    for k, v in row.data.items():
                        cols.append(k)
                        # Basic escaping
                        if isinstance(v, str):
                            safe_v = v.replace("'", "''")
                            vals.append(f"'{safe_v}'")
                        else:
                            vals.append(str(v))
                    
                    sql = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES ({', '.join(vals)});\n"
                    f.write(sql)
            self.log(f"Exported to {filepath}")
        except Exception as e:
            self.log(f"SQL Export failed: {e}")

    def analyze_quality(self) -> Dict[str, Any]:
        """Runs quality analysis on the generated data."""
        if not self.generated_rows:
            return {}
        try:
            df = pd.DataFrame([r.data for r in self.generated_rows])
            return self.analyzer.analyze(df)
        except Exception as e:
            self.log(f"Analysis failed: {e}")
            return {}

    def export_pdf_report(self, filepath: str):
        try:
            metrics = self.analyze_quality()
            self.pdf_exporter.generate_quality_report(metrics, filepath)
            self.log(f"PDF Quality Report exported to {filepath}")
        except Exception as e:
            self.log(f"PDF Export failed: {e}")

    def export_narrative_pdf(self, filepath: str):
        if not self.generated_rows:
            return
            
        try:
            df = pd.DataFrame([r.data for r in self.generated_rows])
            cols = df.columns.tolist()
            if not cols:
                return
                
            # Heuristic: First column is title, rest are body
            # TODO: Make configurable? For now, this is a sensible default for "Narrative Mode"
            title_col = cols[0]
            body_cols = cols[1:]
            
            self.pdf_exporter.generate_narrative_export(df, title_col, body_cols, filepath)
            self.log(f"Narrative PDF exported to {filepath}")
        except Exception as e:
            self.log(f"Narrative Export failed: {e}")

    def get_metrics(self) -> Dict[str, Any]:
        """
        Calculate real-time metrics including token usage, cost, and estimated savings.
        """
        if not self.llm_client:
            return {}

        token_usage = self.llm_client.get_token_usage()
        prompt_tokens = token_usage.get("prompt_tokens", 0)
        completion_tokens = token_usage.get("completion_tokens", 0)
        
        # Calculate Cost
        # Helper for cost
        def calc_cost(prompt, completion):
            return ((prompt / 1_000_000) * self.config.input_price_per_1m) + \
                   ((completion / 1_000_000) * self.config.output_price_per_1m)

        total_cost = calc_cost(prompt_tokens, completion_tokens)
        total_tokens = prompt_tokens + completion_tokens

        # Averages per ROW
        num_rows = len(self.generated_rows)
        if num_rows > 0:
            avg_tokens_in_row = prompt_tokens / num_rows
            avg_tokens_out_row = completion_tokens / num_rows
            avg_tokens_total_row = total_tokens / num_rows
            avg_cost_row = total_cost / num_rows
        else:
            avg_tokens_in_row = 0
            avg_tokens_out_row = 0
            avg_tokens_total_row = 0
            avg_cost_row = 0

        # Savings (est based on Faker cols)
        # Ratio of faker cols to total cols? No, ratio of faker cols to LLM cols.
        # If we have 5 LLM cols and 5 Faker cols, we saved ~100% of the cost (doubled capacity).
        # We estimate based on average cost per LLM column.
        
        llm_cols_count = self.metrics.get("llm_cols", 0)
        faker_cols_count = self.metrics.get("faker_cols", 0)
        
        avg_tokens_per_llm_col = 0
        avg_cost_per_llm_col = 0
        
        if llm_cols_count > 0:
             avg_tokens_per_llm_col = total_tokens / llm_cols_count
             avg_cost_per_llm_col = total_cost / llm_cols_count
             
        saved_tokens = int(faker_cols_count * avg_tokens_per_llm_col)
        saved_cost = faker_cols_count * avg_cost_per_llm_col
        
        # Savings per ROW
        avg_saved_tokens_row = 0
        avg_saved_cost_row = 0
        if num_rows > 0:
            avg_saved_tokens_row = saved_tokens / num_rows
            avg_saved_cost_row = saved_cost / num_rows

        # Stats
        rows_per_sec = 0
        elapsed = 0
        
        start_t = self.metrics.get("start_time")
        end_t = self.metrics.get("end_time")
        last_row_t = self.metrics.get("last_row_time")
        
        if start_t and num_rows > 0:
            # Elapsed is: (end_time if known else now) - start_time
            current_elapsed_ref = end_t if end_t else time.time()
            elapsed = current_elapsed_ref - start_t
            
            # Throughput uses last_row_time to prevent decay while waiting
            # But if we are finished, we use the total elapsed
            calc_ref = end_t if end_t else (last_row_t or time.time())
            
            # Avoid division by zero or negative
            duration = max(0.1, calc_ref - start_t)
            rows_per_sec = num_rows / duration
                
        retry_rate = 0
        total_attempts = self.metrics.get("total_attempts", 0)
        if total_attempts > 0:
            retry_rate = (self.metrics.get("failed_attempts", 0) / total_attempts) * 100

        # Latency Stats
        avg_latency = 0.0
        if self.llm_client and self.llm_client.latency_stats["count"] > 0:
            avg_latency = self.llm_client.latency_stats["total_time"] / self.llm_client.latency_stats["count"]
            
        # ETR (Estimated Time Remaining)
        etr = 0.0
        target_count = len(self.config.existing_data) if self.config.existing_data else self.config.num_rows
        remaining = max(0, target_count - num_rows)
        if rows_per_sec > 0 and remaining > 0:
            etr = remaining / rows_per_sec

        target_count = len(self.columns) # Fallback? No.
        # We need target count to show progress.
        # It is self.config.num_rows usually.
        target_rows = len(self.config.existing_data) if self.config.existing_data else self.config.num_rows

        return {
            "total": {
                "in": prompt_tokens,
                "out": completion_tokens,
                "used": total_tokens,
                "cost": total_cost,
                "saved_tokens": saved_tokens,
                "saved_cost": saved_cost
            },
            "avg_row": {
                 "in": avg_tokens_in_row,
                 "out": avg_tokens_out_row,
                 "used": avg_tokens_total_row,
                 "cost": avg_cost_row,
                 "saved_tokens": avg_saved_tokens_row,
                 "saved_cost": avg_saved_cost_row
            },
            "stats": {
                "throughput": rows_per_sec,
                "retry_rate": retry_rate,
                "elapsed": elapsed,
                "generated": num_rows,
                "target": target_rows,
                "latency": avg_latency,
                "etr": etr
            }
        }

